# Generated by Django 4.1.2 on 2022-10-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_movies_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_images',
            field=models.ImageField(default='blank_profile.png', upload_to='movie_images'),
        ),
    ]
