# Generated by Django 4.1.2 on 2022-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_movies_movie_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='genre_image',
            field=models.ImageField(default='blank_profile.png', upload_to='genre_images'),
        ),
    ]
