# Generated by Django 4.1.2 on 2022-11-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
