# Generated by Django 4.1.2 on 2022-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exam',
        ),
    ]
